language: shell

os:
  - linux
  
arch:
  - ppc64le

env:
  jobs:
    - TORCH_VERSION=1.5.0 TORCHVISION_VERSION=0.6.0 PYTHON_VERSION=3.7 IDX=cpu
  
install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-ppc64le.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create --yes -n test python="${PYTHON_VERSION}"
  - conda activate test
  - conda install pytorch==${TORCH_VERSION} torchvision==${TORCHVISION_VERSION} ${TOOLKIT} -c pytorch -c conda-forge --yes
  - pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}+${IDX}.html
  - pip install cython
  - git clone https://github.com/the-virtual-brain/tvb-geodesic /tmp/gdist
  - cd /tmp/gdist && python setup.py install && cd -
  - pip install scikit-image
  - pip install trimesh
  - pip install flake8 codecov
  - pip install sphinx==3.4.3 sphinx_rtd_theme
  - pip install pandas==1.1.5
  - pip install h5py==3.1.0
  - python setup.py install
script:
  - flake8 .
  - python setup.py test
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cd docs && make clean && make html && cd ..; fi
after_success:
  - codecov
notifications:
  email: false
